const express = require("express");
const { body } = require("express-validator");
const { register, login, getMe } = require("../controllers/authController");
const { protect } = require("../middleware/auth");
const validate = require("../middleware/validate");
const router = express.Router();
router.post("/register", [body("name").trim().notEmpty(), body("email").isEmail(), body("password").isLength({ min: 6 })], validate, register);
router.post("/login",    [body("email").isEmail(), body("password").notEmpty()], validate, login);
router.get("/me", protect, getMe);
module.exports = router;