const express = require("express");
const { body } = require("express-validator");
const { getTasks, createTask, getTask, updateTask, deleteTask, getStats } = require("../controllers/taskController");
const { protect } = require("../middleware/auth");
const validate = require("../middleware/validate");
const router = express.Router();
router.use(protect);
router.get("/stats", getStats);
router.route("/").get(getTasks).post([body("title").trim().notEmpty()], validate, createTask);
router.route("/:id").get(getTask).put(updateTask).delete(deleteTask);
module.exports = router;